// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: proto/gophkeep.proto

package gophkeep

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GophKeep_SaveCredentials_FullMethodName     = "/proto.GophKeep/SaveCredentials"
	GophKeep_GetCredentials_FullMethodName      = "/proto.GophKeep/GetCredentials"
	GophKeep_SaveCard_FullMethodName            = "/proto.GophKeep/SaveCard"
	GophKeep_GetCard_FullMethodName             = "/proto.GophKeep/GetCard"
	GophKeep_SaveAttachment_FullMethodName      = "/proto.GophKeep/SaveAttachment"
	GophKeep_StartSaveFileStream_FullMethodName = "/proto.GophKeep/StartSaveFileStream"
	GophKeep_GetAttachment_FullMethodName       = "/proto.GophKeep/GetAttachment"
	GophKeep_StartGetFileStream_FullMethodName  = "/proto.GophKeep/StartGetFileStream"
	GophKeep_ListAll_FullMethodName             = "/proto.GophKeep/ListAll"
)

// GophKeepClient is the client API for GophKeep service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GophKeepClient interface {
	SaveCredentials(ctx context.Context, in *SaveCredentialsRequest, opts ...grpc.CallOption) (*SaveStatus, error)
	GetCredentials(ctx context.Context, in *GetByMetaRequest, opts ...grpc.CallOption) (*GetCredentialsResponse, error)
	SaveCard(ctx context.Context, in *SaveCardRequest, opts ...grpc.CallOption) (*SaveStatus, error)
	GetCard(ctx context.Context, in *GetByMetaRequest, opts ...grpc.CallOption) (*GetCardResponse, error)
	SaveAttachment(ctx context.Context, in *SaveAttachmentRequest, opts ...grpc.CallOption) (*SaveAttachmentResponse, error)
	StartSaveFileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Chunk, SaveStatus], error)
	GetAttachment(ctx context.Context, in *GetByMetaRequest, opts ...grpc.CallOption) (*GetAttachmentResponse, error)
	StartGetFileStream(ctx context.Context, in *StartGetFileStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error)
	ListAll(ctx context.Context, in *ListAllRequest, opts ...grpc.CallOption) (*ListAllResponse, error)
}

type gophKeepClient struct {
	cc grpc.ClientConnInterface
}

func NewGophKeepClient(cc grpc.ClientConnInterface) GophKeepClient {
	return &gophKeepClient{cc}
}

func (c *gophKeepClient) SaveCredentials(ctx context.Context, in *SaveCredentialsRequest, opts ...grpc.CallOption) (*SaveStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveStatus)
	err := c.cc.Invoke(ctx, GophKeep_SaveCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeepClient) GetCredentials(ctx context.Context, in *GetByMetaRequest, opts ...grpc.CallOption) (*GetCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCredentialsResponse)
	err := c.cc.Invoke(ctx, GophKeep_GetCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeepClient) SaveCard(ctx context.Context, in *SaveCardRequest, opts ...grpc.CallOption) (*SaveStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveStatus)
	err := c.cc.Invoke(ctx, GophKeep_SaveCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeepClient) GetCard(ctx context.Context, in *GetByMetaRequest, opts ...grpc.CallOption) (*GetCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCardResponse)
	err := c.cc.Invoke(ctx, GophKeep_GetCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeepClient) SaveAttachment(ctx context.Context, in *SaveAttachmentRequest, opts ...grpc.CallOption) (*SaveAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveAttachmentResponse)
	err := c.cc.Invoke(ctx, GophKeep_SaveAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeepClient) StartSaveFileStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Chunk, SaveStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GophKeep_ServiceDesc.Streams[0], GophKeep_StartSaveFileStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Chunk, SaveStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GophKeep_StartSaveFileStreamClient = grpc.ClientStreamingClient[Chunk, SaveStatus]

func (c *gophKeepClient) GetAttachment(ctx context.Context, in *GetByMetaRequest, opts ...grpc.CallOption) (*GetAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttachmentResponse)
	err := c.cc.Invoke(ctx, GophKeep_GetAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gophKeepClient) StartGetFileStream(ctx context.Context, in *StartGetFileStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GophKeep_ServiceDesc.Streams[1], GophKeep_StartGetFileStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartGetFileStreamRequest, Chunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GophKeep_StartGetFileStreamClient = grpc.ServerStreamingClient[Chunk]

func (c *gophKeepClient) ListAll(ctx context.Context, in *ListAllRequest, opts ...grpc.CallOption) (*ListAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllResponse)
	err := c.cc.Invoke(ctx, GophKeep_ListAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GophKeepServer is the server API for GophKeep service.
// All implementations must embed UnimplementedGophKeepServer
// for forward compatibility.
type GophKeepServer interface {
	SaveCredentials(context.Context, *SaveCredentialsRequest) (*SaveStatus, error)
	GetCredentials(context.Context, *GetByMetaRequest) (*GetCredentialsResponse, error)
	SaveCard(context.Context, *SaveCardRequest) (*SaveStatus, error)
	GetCard(context.Context, *GetByMetaRequest) (*GetCardResponse, error)
	SaveAttachment(context.Context, *SaveAttachmentRequest) (*SaveAttachmentResponse, error)
	StartSaveFileStream(grpc.ClientStreamingServer[Chunk, SaveStatus]) error
	GetAttachment(context.Context, *GetByMetaRequest) (*GetAttachmentResponse, error)
	StartGetFileStream(*StartGetFileStreamRequest, grpc.ServerStreamingServer[Chunk]) error
	ListAll(context.Context, *ListAllRequest) (*ListAllResponse, error)
	mustEmbedUnimplementedGophKeepServer()
}

// UnimplementedGophKeepServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGophKeepServer struct{}

func (UnimplementedGophKeepServer) SaveCredentials(context.Context, *SaveCredentialsRequest) (*SaveStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveCredentials not implemented")
}
func (UnimplementedGophKeepServer) GetCredentials(context.Context, *GetByMetaRequest) (*GetCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCredentials not implemented")
}
func (UnimplementedGophKeepServer) SaveCard(context.Context, *SaveCardRequest) (*SaveStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveCard not implemented")
}
func (UnimplementedGophKeepServer) GetCard(context.Context, *GetByMetaRequest) (*GetCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCard not implemented")
}
func (UnimplementedGophKeepServer) SaveAttachment(context.Context, *SaveAttachmentRequest) (*SaveAttachmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveAttachment not implemented")
}
func (UnimplementedGophKeepServer) StartSaveFileStream(grpc.ClientStreamingServer[Chunk, SaveStatus]) error {
	return status.Errorf(codes.Unimplemented, "method StartSaveFileStream not implemented")
}
func (UnimplementedGophKeepServer) GetAttachment(context.Context, *GetByMetaRequest) (*GetAttachmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttachment not implemented")
}
func (UnimplementedGophKeepServer) StartGetFileStream(*StartGetFileStreamRequest, grpc.ServerStreamingServer[Chunk]) error {
	return status.Errorf(codes.Unimplemented, "method StartGetFileStream not implemented")
}
func (UnimplementedGophKeepServer) ListAll(context.Context, *ListAllRequest) (*ListAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAll not implemented")
}
func (UnimplementedGophKeepServer) mustEmbedUnimplementedGophKeepServer() {}
func (UnimplementedGophKeepServer) testEmbeddedByValue()                  {}

// UnsafeGophKeepServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GophKeepServer will
// result in compilation errors.
type UnsafeGophKeepServer interface {
	mustEmbedUnimplementedGophKeepServer()
}

func RegisterGophKeepServer(s grpc.ServiceRegistrar, srv GophKeepServer) {
	// If the following call pancis, it indicates UnimplementedGophKeepServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GophKeep_ServiceDesc, srv)
}

func _GophKeep_SaveCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeepServer).SaveCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeep_SaveCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeepServer).SaveCredentials(ctx, req.(*SaveCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeep_GetCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeepServer).GetCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeep_GetCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeepServer).GetCredentials(ctx, req.(*GetByMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeep_SaveCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeepServer).SaveCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeep_SaveCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeepServer).SaveCard(ctx, req.(*SaveCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeep_GetCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeepServer).GetCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeep_GetCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeepServer).GetCard(ctx, req.(*GetByMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeep_SaveAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeepServer).SaveAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeep_SaveAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeepServer).SaveAttachment(ctx, req.(*SaveAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeep_StartSaveFileStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GophKeepServer).StartSaveFileStream(&grpc.GenericServerStream[Chunk, SaveStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GophKeep_StartSaveFileStreamServer = grpc.ClientStreamingServer[Chunk, SaveStatus]

func _GophKeep_GetAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeepServer).GetAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeep_GetAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeepServer).GetAttachment(ctx, req.(*GetByMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GophKeep_StartGetFileStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartGetFileStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GophKeepServer).StartGetFileStream(m, &grpc.GenericServerStream[StartGetFileStreamRequest, Chunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GophKeep_StartGetFileStreamServer = grpc.ServerStreamingServer[Chunk]

func _GophKeep_ListAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GophKeepServer).ListAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GophKeep_ListAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GophKeepServer).ListAll(ctx, req.(*ListAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GophKeep_ServiceDesc is the grpc.ServiceDesc for GophKeep service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GophKeep_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GophKeep",
	HandlerType: (*GophKeepServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveCredentials",
			Handler:    _GophKeep_SaveCredentials_Handler,
		},
		{
			MethodName: "GetCredentials",
			Handler:    _GophKeep_GetCredentials_Handler,
		},
		{
			MethodName: "SaveCard",
			Handler:    _GophKeep_SaveCard_Handler,
		},
		{
			MethodName: "GetCard",
			Handler:    _GophKeep_GetCard_Handler,
		},
		{
			MethodName: "SaveAttachment",
			Handler:    _GophKeep_SaveAttachment_Handler,
		},
		{
			MethodName: "GetAttachment",
			Handler:    _GophKeep_GetAttachment_Handler,
		},
		{
			MethodName: "ListAll",
			Handler:    _GophKeep_ListAll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartSaveFileStream",
			Handler:       _GophKeep_StartSaveFileStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StartGetFileStream",
			Handler:       _GophKeep_StartGetFileStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/gophkeep.proto",
}
